'use client'
import '@/styles/reset.css'
import '@/styles/globals.css'
import '@/styles/fonts.css'

import Header from '@/components/header'
import Footer from '@/components/footer'
import SignIn from '@/components/singin'
import {Provider} from "react-redux";
import store from "@/store";

export const metadata = {
    title: 'Find Developer',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {

    return (
        <html lang="en">
        <body className={`markpro scroll-none`}>
        <Provider store={store}>
            <Header/>
            <main>{children}</main>
            <SignIn/>
            <Footer/>
        </Provider>
        </body>
        </html>
    )
}
